# Generated by Django 2.2.8 on 2020-02-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_v370_unifiedjob_dependencies_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='webhook_service',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea')], help_text='Service that webhook requests will be accepted from', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='webhook_service',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea')], help_text='Service that webhook requests will be accepted from', max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowjob',
            name='webhook_service',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea')], help_text='Service that webhook requests will be accepted from', max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowjobtemplate',
            name='webhook_service',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea')], help_text='Service that webhook requests will be accepted from', max_length=16),
        ),
    ]
